name: Android Build

on:
  push:
    branches:
      - master # Or your default branch like master
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11' # Use Java 11, common for Android projects

    - name: Set up Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: wrapper # Use the project's wrapper version

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: TacoClient/

    - name: Build TacoClient Debug APK
      run: ./gradlew assembleDebug
      working-directory: TacoClient/

    - name: Find TacoClient APK
      id: find_apks
      run: |
        echo "TACO_CLIENT_APK=$(find ./TacoClient/app/build/outputs/apk/debug -name "*.apk" -print -quit)" >> $GITHUB_OUTPUT
        echo "TACO_CLIENT_APK_NAME=$(basename $(find ./TacoClient/app/build/outputs/apk/debug -name "*.apk" -print -quit))" >> $GITHUB_OUTPUT

    - name: Upload Artifact (on Push)
      if: github.event_name == 'push'
      uses: actions/upload-artifact@v4
      with:
        name: tacoclient-debug-apk
        path: ${{ steps.find_apks.outputs.TACO_CLIENT_APK }}

    - name: Upload TacoClient APK to Release (on Release Create)
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v2
      with:
        files: ${{ steps.find_apks.outputs.TACO_CLIENT_APK }}
        tag_name: ${{ github.ref }}
        name: ${{ github.ref }}
        body: See the [commit history](https://github.com/${{ github.repository }}/commits/${{ github.sha }}).
        prerelease: contains(github.ref, '-rc')
        generate_release_notes: false
        draft: false
        fail_on_error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
